# Write your MySQL query statement below
SELECT P.product_id, ROUND(IFNULL(SUM(P.PRICE * U.UNITS)/SUM(U.UNITS), 0), 2) AS average_price FROM PRICES P LEFT JOIN UNITSSOLD U
ON P.PRODUCT_ID = U.PRODUCT_ID AND
 U.PURCHASE_DATE >=P.START_DATE AND U.PURCHASE_DATE<=P.END_DATE
GROUP BY P.PRODUCT_ID;
