SELECT ROUND(SUM(CASE WHEN DATEDIFF(A.EVENT_DATE, A.MIN_EVENT_DATE)=1 THEN 1 ELSE 0 END)/COUNT(DISTINCT A.PLAYER_ID), 2) AS FRACTION FROM (SELECT PLAYER_ID, EVENT_DATE, MIN(EVENT_DATE) OVER(PARTITION BY PLAYER_ID) AS MIN_EVENT_DATE FROM ACTIVITY) A

-- SELECT ROUND( SUM(CASE WHEN DATEDIFF(A.EVENT_DATE, (SELECT MIN(EVENT_DATE) FROM ACTIVITY WHERE PLAYER_ID = A.PLAYER_ID ))=1 THEN 1 ELSE 0 END)/COUNT(DISTINCT PLAYER_ID) , 2)AS fraction FROM ACTIVITY A 
