# Write your MySQL query statement below
SELECT ROUND((SUM(CASE WHEN T.DATE=T.PREF_DATE THEN 1 ELSE 0 END)/COUNT(T.CUSTOMER_ID))*100, 2) AS immediate_percentage FROM (
SELECT CUSTOMER_ID, MIN(ORDER_DATE) AS DATE, MIN(CUSTOMER_PREF_DELIVERY_DATE) AS PREF_DATE FROM DELIVERY GROUP BY CUSTOMER_ID) T; 
-- SELECT ROUND( 
--     ( SUM(CASE WHEN RANKING = 1 AND ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 1 ELSE 0 END)/
--     SUM(CASE WHEN RANKING = 1 THEN 1 ELSE 0 END) )*100, 2) AS immediate_percentage FROM 
-- ( SELECT CUSTOMER_ID, ORDER_DATE, CUSTOMER_PREF_DELIVERY_DATE, RANK() OVER( PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE) AS "RANKING" FROM DELIVERY ) T
