SELECT E1.name FROM EMPLOYEE E1 JOIN (SELECT MANAGERID, COUNT(*) AS TEU FROM EMPLOYEE GROUP BY MANAGERID)E2 
ON E1.ID = E2.MANAGERID WHERE TEU>4 ORDER BY E1.ID

-- SELECT E1.name FROM EMPLOYEE E1 JOIN EMPLOYEE E2 
-- ON E1.ID = E2.MANAGERID GROUP BY E1.ID
-- HAVING COUNT(*)>4;
