# Write your MySQL query statement below
SELECT CONTEST_ID, ROUND( (COUNT(*)/T.TOT)*100 , 2) AS PERCENTAGE FROM (SELECT COUNT(*) AS TOT FROM USERS) T CROSS JOIN USERS U JOIN REGISTER R 
ON U.USER_ID = R.USER_ID
GROUP BY CONTEST_ID ORDER BY PERCENTAGE DESC, CONTEST_ID ASC
