SELECT S.student_id, S.student_name, SB.subject_name, COUNT(EX.SUBJECT_NAME) AS attended_exams from STUDENTS S 
CROSS JOIN SUBJECTS SB 
LEFT JOIN EXAMINATIONS EX ON S.STUDENT_ID = EX.STUDENT_ID AND SB.SUBJECT_NAME = EX.SUBJECT_NAME
GROUP BY S.STUDENT_ID, SB.SUBJECT_NAME 
ORDER BY S.STUDENT_ID, SB.SUBJECT_NAME; 
